[versions]
android-compileSdk = "35"
android-buildTools = "35.0.0"
android-minSdk = "21"
android-targetSdk = "35"
agp = "8.8.0"
androidx-activity = "1.9.3"
androidx-core = "1.15.0"
androidx-annotation = "1.9.1"
androidx-appcompat = "1.7.0"
androidx-fragment = "1.8.5"
androidx-recyclerview = "1.3.2"
kotlin = "2.1.0"
leakcanary = "2.7"
vbpd-version = "2.0.0-alpha02"
vanniktechMavenPublish = "0.30.0"
jvmTarget = "21"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-viewbinding = { module = "androidx.databinding:viewbinding", version.ref = "agp" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

gradleplugins-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradleplugins-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradleplugins-vanniktechMavenPublish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "vanniktechMavenPublish" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
