build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 15
    thresholdInInterfaces: 10

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

exceptions:
  SwallowedException:
    ignoredExceptionTypes:
      - NoSuchMethodException

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  MatchingDeclarationName:
    active: false
  MemberNameEqualsClassName:
    active: false

style:
  MaxLineLength:
    active: false
  WildcardImport:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    max: 3
  UnusedPrivateMember:
    active: true
