build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 15
    thresholdInInterfaces: 10

style:
  MaxLineLength:
    maxLineLength: 120
  WildcardImport:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    max: 3
  UnusedPrivateMember:
    active: true

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
